---
# roles/cockpit/tasks/main.yml

- name: "Check if SSH password authentication is already enabled"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/02-enable-passwords.conf
    line: "PasswordAuthentication yes"
    state: absent
  check_mode: true
  register: ssh_password_check
  failed_when: false

- name: "Check main sshd_config for password authentication"
  ansible.builtin.command:
    cmd: grep -E "^PasswordAuthentication\s+(yes|no)" /etc/ssh/sshd_config
  register: main_sshd_config_check
  failed_when: false
  changed_when: false

- name: "Enable SSH password authentication if not already enabled"
  ansible.builtin.copy:
    content: "PasswordAuthentication yes\n"
    dest: /etc/ssh/sshd_config.d/02-enable-passwords.conf
    mode: '0644'
  when: 
    - ssh_password_check.found == 0
    - "'PasswordAuthentication yes' not in main_sshd_config_check.stdout"
  notify: Restart sshd

- name: "Install Cockpit packages as overlay RPMs"
  community.general.rpm_ostree_pkg:
    name:
      - cockpit-system
      - cockpit-ostree
      - cockpit-podman
      - cockpit-networkmanager
    state: present
  notify: Reboot to apply OS changes

- name: "Flush handlers to reboot if needed"
  meta: flush_handlers

- name: "Run Cockpit web service container"
  ansible.builtin.command:
    cmd: podman container runlabel --name cockpit-ws RUN quay.io/cockpit/ws
  register: cockpit_run_result
  failed_when: false
  changed_when: cockpit_run_result.rc == 0

- name: "Install Cockpit systemd service"
  ansible.builtin.command:
    cmd: podman container runlabel INSTALL quay.io/cockpit/ws
  register: cockpit_install_result
  failed_when: false
  changed_when: cockpit_install_result.rc == 0

- name: "Enable and start Cockpit service"
  ansible.builtin.systemd:
    name: "{{ cockpit_service_name }}"
    state: started
    enabled: true

- name: "Configure firewall for Cockpit"
  ansible.posix.firewalld:
    service: "{{ cockpit_firewall_service }}"
    permanent: true
    state: enabled
    immediate: true

- name: "Display Cockpit access information"
  ansible.builtin.debug:
    msg: |
      Cockpit Web Interface is available at:
      https://{{ ansible_default_ipv4.address }}:{{ cockpit_port }}
      
      Use your system user credentials to log in.
      
      Note: First-time access may show a security warning
      due to self-signed certificates. This is normal.

- name: Set Cockpit branding directory fact
  set_fact:
    cockpit_branding_dir: "/usr/share/cockpit/branding/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"

- name: Ensure Cockpit branding directory exists
  ansible.builtin.file:
    path: "{{ cockpit_branding_dir }}"
    state: directory
    mode: '0755'

- name: Copy custom logo if defined
  ansible.builtin.copy:
    src: "{{ cockpit_logo | default(omit) }}"
    dest: "{{ cockpit_branding_dir }}/logo.png"
    mode: '0644'
  when: cockpit_logo is defined

- name: Copy custom favicon if defined
  ansible.builtin.copy:
    src: "{{ cockpit_favicon | default(omit) }}"
    dest: "{{ cockpit_branding_dir }}/favicon.ico"
    mode: '0644'
  when: cockpit_favicon is defined

- name: Copy custom apple-touch-icon if defined
  ansible.builtin.copy:
    src: "{{ cockpit_apple_touch_icon | default(omit) }}"
    dest: "{{ cockpit_branding_dir }}/apple-touch-icon.png"
    mode: '0644'
  when: cockpit_apple_touch_icon is defined

- name: Copy custom background if defined
  ansible.builtin.copy:
    src: "{{ cockpit_background | default(omit) }}"
    dest: "{{ cockpit_branding_dir }}/background.jpg"
    mode: '0644'
  when: cockpit_background is defined

- name: Copy custom CSS if defined
  ansible.builtin.copy:
    src: "{{ cockpit_css | default(omit) }}"
    dest: "{{ cockpit_branding_dir }}/branding.css"
    mode: '0644'
  when: cockpit_css is defined
