---
# Ansible Galaxy requirements for nas-server

# Collections
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.crypto
    version: ">=2.0.0"

# Roles
roles:
  - name: geerlingguy.docker
    version: "6.0.4"
  - name: geerlingguy.nginx
    version: "3.0.0"