---
# roles/nfs-server/defaults/main.yml

# NFS Server Container Settings
nfs_container_name: "nfs-server"
nfs_container_image: "docker.io/gists/nfs-server"

# NFS Export Path Configuration
nfs_main_export_name: "shared"
nfs_base_path: "/var/srv/nfs"
nfs_export_path: "{{ nfs_base_path }}/{{ nfs_main_export_name }}"

# Drive Configuration
nfs_drives: []

# Network and Firewall Settings
nfs_host_port: 2049
nfs_firewall_service: "nfs"

# Quadlet directory
nfs_quadlet_dir: "/etc/containers/systemd/"
