---
- name: "FORMAT | Create filesystem on applicable drives"
  filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.encrypt | default(false) | ternary('/dev/mapper/' + item.luks_name, item.device) }}"
  loop: "{{ storage_drives | selectattr('format', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"

- name: "MOUNT | Persistently mount all drives"
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.encrypt | default(false) | ternary('/dev/mapper/' + item.luks_name, item.device) }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.mount_options | default('defaults,noatime') }}"
    state: present
  loop: "{{ storage_drives }}"
  loop_control:
    label: "{{ item.name }}"