---
# Molecule converge playbook - tests full deployment
# Skips hardware-dependent roles (encrypt, mount)

- name: Converge - Test containerized services
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      
    - name: Install required packages for testing
      package:
        name:
          - podman
          - systemd
          - firewalld
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Start and enable systemd services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - systemd-logind
        - firewalld
      ignore_errors: true
      
    - name: Create mock mount points for testing
      file:
        path: "{{ item.mount_point }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ storage_drives }}"
      when: storage_drives is defined
      
    - name: Create test content in mock storage
      copy:
        content: "Test content for {{ item.name }}"
        dest: "{{ item.mount_point }}/test-file.txt"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0644"
      loop: "{{ storage_drives }}"
      when: storage_drives is defined
  
  roles:
    # Skip encrypt and mount roles - they require real hardware
    # - encrypt    # Requires real block devices and LUKS
    # - mount      # Requires real filesystems
    
    # Test containerized services
    - role: samba-server
      when: storage_drives | selectattr('samba_share', 'equalto', true) | list | length > 0
      
    - role: nfs-server  
      when: storage_drives | selectattr('nfs_export', 'equalto', true) | list | length > 0
      
    - role: vuetorrent
      
    - role: cockpit
