---
# Samba role-specific converge playbook

- name: Converge - Test Samba Server
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Install required packages
      package:
        name:
          - podman
          - systemd
          - firewalld
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true
      ignore_errors: true
      
    - name: Create mock Samba storage directory
      file:
        path: "{{ item.mount_point }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ storage_drives }}"
      when: item.samba_share | default(false)
      
    - name: Create test content for Samba
      copy:
        content: |
          Test Samba Share Content
          ======================
          This is test content for the {{ item.name }} share.
          Created for Molecule testing.
        dest: "{{ item.mount_point }}/samba-test.txt"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0644"
      loop: "{{ storage_drives }}"
      when: item.samba_share | default(false)
  
  roles:
    - role: samba-server
