---
# roles/cockpit/handlers/main.yml

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Reboot to apply OS changes
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: uptime

- name: Restart Cockpit service
  ansible.builtin.systemd:
    name: cockpit.service
    state: restarted
