---
- name: Gather disk facts
  setup:
    gather_subset:
      - hardware

- name: Get all block devices
  command: lsblk -J -o NAME,SIZE,TYPE,MOUNTPOINT,FSTYPE
  register: lsblk_output
  changed_when: false

- name: Parse block devices
  set_fact:
    all_block_devices: "{{ (lsblk_output.stdout | from_json).blockdevices }}"

- name: Find root device
  set_fact:
    root_device: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='device') | first | regex_replace('[0-9]+$', '') }}"

- name: Filter available drives for NFS
  set_fact:
    available_drives: >-
      {{
        all_block_devices
        | selectattr('type', 'equalto', 'disk')
        | rejectattr('name', 'in', exclude_drives)
        | selectattr('size', 'match', '^[0-9]+\.[0-9]+[GT]$')
        | list
      }}

- name: Filter non-OS drives
  set_fact:
    non_os_drives: >-
      {{
        available_drives
        | rejectattr('name', 'equalto', root_device | basename)
        | list
      }}

- name: Auto-generate NFS drives list (all drives)
  set_fact:
    nfs_drives: >-
      {{
        available_drives
        | map('dict_combine', {
          'name': item.name,
          'device': '/dev/' + item.name + '1',
          'mount_point': '/mnt/' + item.name,
          'fstype': 'ext4',
          'mount_options': 'defaults,noatime'
        })
        | list
      }}
  when: all_drives | bool and (nfs_drives | length == 0)
  loop: "{{ available_drives }}"
  loop_control:
    loop_var: item

- name: Auto-generate NFS drives list (non-OS drives only)
  set_fact:
    nfs_drives: >-
      {{
        non_os_drives
        | map('dict_combine', {
          'name': item.name,
          'device': '/dev/' + item.name + '1',
          'mount_point': '/mnt/' + item.name,
          'fstype': 'ext4',
          'mount_options': 'defaults,noatime'
        })
        | list
      }}
  when: all_non_os_drives | bool and (nfs_drives | length == 0)
  loop: "{{ non_os_drives }}"
  loop_control:
    loop_var: item

- name: Display discovered drives
  debug:
    msg: |
      Root device: {{ root_device }}
      Available drives: {{ available_drives | map(attribute='name') | list }}
      Non-OS drives: {{ non_os_drives | map(attribute='name') | list }}
      Selected NFS drives: {{ nfs_drives | map(attribute='name') | list }}